version: 2

project_name: seed-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: seed-cli
    main: ./cmd/seed-cli
    binary: seed-cli
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: seed-cli
    builds: [seed-cli]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: inikalaev
    name: database-seed-cli
  draft: false
  prerelease: auto
