package sqlemit_test

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/ivannikolaev/seed-cli/cli/internal/config"
	"github.com/ivannikolaev/seed-cli/cli/internal/registry"
	"github.com/ivannikolaev/seed-cli/cli/internal/relations"
	"github.com/ivannikolaev/seed-cli/cli/internal/sqlemit"
)

// updateGolden lets contributors refresh the golden SQL after an intentional
// behaviour change: `go test ./internal/sqlemit -run TestGolden -update`.
var updateGolden = flag.Bool("update", false, "update golden expected.sql")

// TestGoldenGenerate is an end-to-end regression guard for the full pipeline:
// config.Load → relations.Build → sqlemit.Emit. It pins a realistic fixture
// (customers+orders with FK, enum, numeric, timestamptz) so any accidental
// behaviour change surfaces as a diff in testdata/golden/expected.sql.
//
// Intentional changes: inspect the diff, then run with -update to rewrite the
// golden. Unintentional changes: fix the code.
func TestGoldenGenerate(t *testing.T) {
	// Repo root relative to this test file.
	root := filepath.Join("..", "..", "testdata", "golden")

	cfg, err := config.Load(filepath.Join(root, "seed.yaml"))
	if err != nil {
		t.Fatalf("load golden config: %v", err)
	}
	g, err := relations.Build(cfg)
	if err != nil {
		t.Fatalf("build relations: %v", err)
	}
	plan := g.PlanFor(cfg)
	em := sqlemit.New(cfg, registry.Default(), plan, sqlemit.Options{
		Locale: cfg.Defaults.Locale,
		Seed:   cfg.Defaults.Seed,
	})
	var got bytes.Buffer
	if err := em.Emit(&got); err != nil {
		t.Fatalf("emit: %v", err)
	}

	goldenPath := filepath.Join(root, "expected.sql")
	normalized := normalizeSQL(got.Bytes())

	if *updateGolden {
		if err := os.WriteFile(goldenPath, normalized, 0o644); err != nil {
			t.Fatalf("update golden: %v", err)
		}
		t.Logf("updated %s", goldenPath)
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if !bytes.Equal(normalized, want) {
		t.Errorf("generated SQL diverged from golden.\nRun with -update after reviewing the diff:\n  go test ./internal/sqlemit -run TestGolden -update\n\n--- got ---\n%s\n--- want ---\n%s", normalized, want)
	}
}

// normalizeSQL replaces the generation timestamp with a fixed placeholder so
// the golden file stays byte-stable across runs.
var timestampLine = regexp.MustCompile(`-- Generated by seed CLI at [^\n]+`)

func normalizeSQL(b []byte) []byte {
	return timestampLine.ReplaceAll(b, []byte("-- Generated by seed CLI at <TIMESTAMP>"))
}
