// Package sqlemit turns a resolved config + relations plan into a PostgreSQL
// seed script. No DB connection required — generation is pure: input is the
// model, output is UTF-8 SQL on an io.Writer.
package sqlemit

import (
	"encoding/json"
	"fmt"
	"io"
	"math/rand/v2"
	"sort"
	"strings"
	"time"

	"github.com/ivannikolaev/seed-cli/cli/internal/config"
	"github.com/ivannikolaev/seed-cli/cli/internal/registry"
	"github.com/ivannikolaev/seed-cli/cli/internal/relations"
	"github.com/ivannikolaev/seed-cli/cli/pkg/seedapi"
)

type Options struct {
	Locale     string
	Seed       int64
	BatchSize  int
}

type Emitter struct {
	cfg  *config.Config
	reg  *registry.Registry
	plan *relations.Plan
	opts Options
	pool *memoryPool
}

func New(cfg *config.Config, reg *registry.Registry, plan *relations.Plan, opts Options) *Emitter {
	if opts.BatchSize <= 0 {
		opts.BatchSize = 500
	}
	return &Emitter{cfg: cfg, reg: reg, plan: plan, opts: opts, pool: newMemoryPool()}
}

func (e *Emitter) Emit(w io.Writer) error {
	rng := rand.New(rand.NewPCG(uint64(e.opts.Seed), uint64(e.opts.Seed)^0x9E3779B97F4A7C15))
	fmt.Fprintf(w, "-- Generated by seed CLI at %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintln(w, "BEGIN;")
	if len(e.plan.Cycles) > 0 {
		fmt.Fprintln(w, "SET CONSTRAINTS ALL DEFERRED;")
	}
	for _, ref := range e.plan.Order {
		key := ref.Key()
		tbl := e.cfg.Tables[key]
		if tbl == nil || tbl.Removed {
			continue
		}
		count := e.plan.RowCounts[key]
		if count <= 0 {
			continue
		}
		if err := e.emitTable(w, ref, tbl, count, rng); err != nil {
			return err
		}
	}
	fmt.Fprintln(w, "COMMIT;")
	return nil
}

func (e *Emitter) emitTable(w io.Writer, ref relations.TableRef, tbl *config.Table, count int, rng *rand.Rand) error {
	cols := activeColumns(tbl)
	if len(cols) == 0 {
		return nil
	}
	fmt.Fprintf(w, "\n-- %s (%d rows)\n", ref.Key(), count)

	qname := quoteIdent(ref.Schema) + "." + quoteIdent(ref.Name)
	colList := make([]string, len(cols))
	for i, c := range cols {
		colList[i] = quoteIdent(c)
	}

	batch := e.opts.BatchSize
	for start := 0; start < count; start += batch {
		end := start + batch
		if end > count {
			end = count
		}
		fmt.Fprintf(w, "INSERT INTO %s (%s) VALUES\n", qname, strings.Join(colList, ", "))
		for row := start; row < end; row++ {
			values := make([]string, len(cols))
			for i, colName := range cols {
				spec := tbl.Columns[colName]
				val := e.generateValue(ref, colName, spec, row, rng)
				values[i] = formatSQL(val, spec)
				if isPKColumn(tbl, colName) {
					e.pool.add(ref.Schema, ref.Name, colName, val)
				}
			}
			sep := ","
			if row == end-1 {
				sep = ";"
			}
			fmt.Fprintf(w, "  (%s)%s\n", strings.Join(values, ", "), sep)
		}
	}
	return nil
}

func isPKColumn(tbl *config.Table, name string) bool {
	if len(tbl.PKOrder) > 0 {
		return tbl.PKOrder[0] == name
	}
	return name == "id"
}

func activeColumns(tbl *config.Table) []string {
	order := append([]string{}, tbl.PKOrder...)
	seen := map[string]bool{}
	var out []string
	for _, name := range order {
		if spec, ok := tbl.Columns[name]; ok && !spec.Removed {
			out = append(out, name)
			seen[name] = true
		}
	}
	rest := make([]string, 0)
	for name, spec := range tbl.Columns {
		if !seen[name] && !spec.Removed {
			rest = append(rest, name)
		}
	}
	sort.Strings(rest)
	return append(out, rest...)
}

func (e *Emitter) generateValue(ref relations.TableRef, colName string, spec *config.ColumnSpec, row int, rng *rand.Rand) any {
	// Literal value — emitted as-is for every row.
	if spec.Value != nil {
		return spec.Value
	}
	// JSON shape defined inline — build object recursively, skip mechanism.
	if len(spec.Values) > 0 {
		obj := e.buildJSONObject(ref, spec.Values, row, rng)
		b, _ := json.Marshal(obj)
		return string(b)
	}
	m, ok := e.reg.Get(spec.Mechanism)
	if !ok {
		return nil
	}
	apiCol := seedapi.Column{
		Schema: ref.Schema, Table: ref.Name, Name: colName,
		DataType: spec.DataType, Nullable: spec.Nullable,
	}
	if target, _ := spec.Params["target"].(string); target != "" {
		apiCol.FKTarget = target
	}
	return m.Generate(seedapi.GenContext{
		Column: apiCol,
		Row:    row,
		Rng:    rng,
		Params: seedapi.Params(spec.Params),
		FKPool: e.pool,
		Locale: e.opts.Locale,
	})
}

// buildJSONObject recursively builds a map[string]any from a Values spec.
// Nested Values entries produce nested maps; leaf entries call the mechanism.
func (e *Emitter) buildJSONObject(ref relations.TableRef, values map[string]*config.ColumnSpec, row int, rng *rand.Rand) map[string]any {
	obj := make(map[string]any, len(values))
	for k, spec := range values {
		if spec.Value != nil {
			obj[k] = spec.Value
			continue
		}
		if len(spec.Values) > 0 {
			obj[k] = e.buildJSONObject(ref, spec.Values, row, rng)
		} else {
			m, ok := e.reg.Get(spec.Mechanism)
			if !ok {
				obj[k] = nil
				continue
			}
			apiCol := seedapi.Column{
				Schema: ref.Schema, Table: ref.Name, Name: k,
				DataType: spec.DataType, Nullable: spec.Nullable,
			}
			obj[k] = m.Generate(seedapi.GenContext{
				Column: apiCol,
				Row:    row,
				Rng:    rng,
				Params: seedapi.Params(spec.Params),
				FKPool: e.pool,
				Locale: e.opts.Locale,
			})
		}
	}
	return obj
}

func formatSQL(v any, spec *config.ColumnSpec) string {
	if v == nil {
		return "NULL"
	}
	switch x := v.(type) {
	case string:
		return "'" + strings.ReplaceAll(x, "'", "''") + "'"
	case bool:
		if x {
			return "TRUE"
		}
		return "FALSE"
	case int:
		return fmt.Sprintf("%d", x)
	case int64:
		return fmt.Sprintf("%d", x)
	case float64:
		if spec != nil && strings.Contains(strings.ToLower(spec.DataType), "json") {
			return "'" + fmt.Sprintf("%g", x) + "'"
		}
		return fmt.Sprintf("%g", x)
	default:
		return "'" + strings.ReplaceAll(fmt.Sprint(x), "'", "''") + "'"
	}
}

func quoteIdent(s string) string {
	return "\"" + strings.ReplaceAll(s, "\"", "\"\"") + "\""
}

// memoryPool keeps already-generated PKs for FK sampling.
type memoryPool struct {
	byKey map[string][]any
}

func newMemoryPool() *memoryPool { return &memoryPool{byKey: map[string][]any{}} }

func (p *memoryPool) add(schemaName, table, column string, v any) {
	if v == nil {
		return
	}
	k := schemaName + "." + table + "." + column
	p.byKey[k] = append(p.byKey[k], v)
}

func (p *memoryPool) Pick(schemaName, table, column string, rng *rand.Rand) (any, bool) {
	k := schemaName + "." + table + "." + column
	pool := p.byKey[k]
	if len(pool) == 0 {
		return nil, false
	}
	return pool[rng.IntN(len(pool))], true
}
