// Package sqlemit turns a resolved config + relations plan into a PostgreSQL
// seed script. No DB connection required — generation is pure: input is the
// model, output is UTF-8 SQL on an io.Writer.
package sqlemit

import (
	"encoding/json"
	"fmt"
	"io"
	"math"
	"math/rand/v2"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/inikalaev/database-seed-cli/internal/config"
	"github.com/inikalaev/database-seed-cli/internal/registry"
	"github.com/inikalaev/database-seed-cli/internal/relations"
	"github.com/inikalaev/database-seed-cli/pkg/seedapi"
)

type Options struct {
	Locale     string
	Seed       int64
	BatchSize  int
}

type Emitter struct {
	cfg  *config.Config
	reg  *registry.Registry
	plan *relations.Plan
	opts Options
	pool *memoryPool
	// drops tracks per-table uniqueness collisions that couldn't be resolved
	// by resampling. Populated during Emit; accessible via Drops() so the
	// `generate` command can warn the user about truncated row counts.
	drops map[string]DropInfo
}

// DropInfo summarises how an emitted table diverged from the planned row count.
type DropInfo struct {
	Requested int
	Emitted   int
	// Reason is a short tag for the loudest cause of the divergence. Only
	// "unique_collision" is set today; kept as a string to leave room for
	// future causes (e.g., FK pool shortfall) without a breaking API change.
	Reason string
}

// MaxUniqueRetries caps resampling attempts per row on a unique-key collision.
// 50 is generous enough for dense composite UNIQUE pools (e.g. M×N fkref pairs
// where M,N ≥ 8 yields < 1% miss rate after 50 tries) while keeping worst-case
// generation time bounded when collisions are unsolvable.
const MaxUniqueRetries = 50

func New(cfg *config.Config, reg *registry.Registry, plan *relations.Plan, opts Options) *Emitter {
	if opts.BatchSize <= 0 {
		opts.BatchSize = 500
	}
	return &Emitter{cfg: cfg, reg: reg, plan: plan, opts: opts}
}

// Drops returns the per-table drop summary from the most recent Emit call.
// Tables that emitted their full requested count are omitted.
func (e *Emitter) Drops() map[string]DropInfo {
	return e.drops
}

func (e *Emitter) Emit(w io.Writer) error {
	// Fresh pool per call — otherwise repeated Emits leak PKs across runs.
	e.pool = newMemoryPool()
	e.drops = map[string]DropInfo{}
	rng := rand.New(rand.NewPCG(uint64(e.opts.Seed), uint64(e.opts.Seed)^0x9E3779B97F4A7C15))
	fmt.Fprintf(w, "-- Generated by seed CLI at %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintln(w, "BEGIN;")
	if len(e.plan.Cycles) > 0 {
		fmt.Fprintln(w, "SET CONSTRAINTS ALL DEFERRED;")
	}
	for _, ref := range e.plan.Order {
		key := ref.Key()
		tbl := e.cfg.Tables[key]
		if tbl == nil || tbl.Removed {
			continue
		}
		count := e.plan.RowCounts[key]
		if count <= 0 {
			continue
		}
		if err := e.emitTable(w, ref, tbl, count, rng); err != nil {
			return err
		}
	}
	fmt.Fprintln(w, "COMMIT;")
	return nil
}

func (e *Emitter) emitTable(w io.Writer, ref relations.TableRef, tbl *config.Table, count int, rng *rand.Rand) error {
	cols := activeColumns(tbl)
	if len(cols) == 0 {
		return nil
	}
	fmt.Fprintf(w, "\n-- %s (%d rows)\n", ref.Key(), count)

	qname := quoteIdent(ref.Schema) + "." + quoteIdent(ref.Name)
	colList := make([]string, len(cols))
	for i, c := range cols {
		colList[i] = quoteIdent(c)
	}

	isPK := make([]bool, len(cols))
	for i, name := range cols {
		isPK[i] = isPKColumn(tbl, name)
	}
	tracker := buildUniqueTracker(tbl, cols)
	poly := buildPolyPlan(tbl, cols)

	rowVals := make([]any, len(cols))
	emittedTotal := 0
	dropped := 0
	// Rows are emitted in batches. Each batch is a separate INSERT statement;
	// rows dropped by the uniqueness tracker are simply excluded from the
	// current batch's INSERT list rather than skipping a pass through the
	// outer loop.
	batch := e.opts.BatchSize
	for start := 0; start < count; start += batch {
		end := start + batch
		if end > count {
			end = count
		}
		rendered := make([][]string, 0, end-start)
		for row := start; row < end; row++ {
			keep, err := e.generateRow(ref, tbl, cols, rowVals, isPK, tracker, poly, row, rng)
			if err != nil {
				return err
			}
			if !keep {
				dropped++
				continue
			}
			tracker.commit(rowVals)
			values := make([]string, len(cols))
			for i, val := range rowVals {
				values[i] = formatSQL(val)
			}
			rendered = append(rendered, values)
		}
		if len(rendered) == 0 {
			continue
		}
		fmt.Fprintf(w, "INSERT INTO %s (%s) VALUES\n", qname, strings.Join(colList, ", "))
		for i, vals := range rendered {
			sep := ","
			if i == len(rendered)-1 {
				sep = ";"
			}
			fmt.Fprintf(w, "  (%s)%s\n", strings.Join(vals, ", "), sep)
		}
		emittedTotal += len(rendered)
	}
	if dropped > 0 {
		e.drops[ref.Key()] = DropInfo{
			Requested: count,
			Emitted:   emittedTotal,
			Reason:    "unique_collision",
		}
	}
	return nil
}

// generateRow fills rowVals once (or up to MaxUniqueRetries times on unique
// collisions) and returns whether the row should be kept. Each resample runs
// every column's factory again, so fkref picks a fresh parent PK and random
// factories advance the rng — the only columns unchanged across attempts are
// literal Value columns and row-indexed factories like pk_serial.
//
// PK columns are added to the FK pool *during* column iteration (not after
// the whole row) so self-FK columns in the same row can sample the just-
// generated PK. To keep retries clean the pool is snapshotted before each
// attempt and rolled back on collision or on final drop.
func (e *Emitter) generateRow(ref relations.TableRef, tbl *config.Table, cols []string, rowVals []any, isPK []bool, tracker *uniqueTracker, poly *polyPlan, row int, rng *rand.Rand) (bool, error) {
	snap := e.pool.snapshot(ref.Schema, ref.Name)
	for attempt := 0; attempt <= MaxUniqueRetries; attempt++ {
		if attempt > 0 {
			e.pool.restore(snap)
		}
		// Polymorphic pairs generate before the column loop so the picked
		// `_type`/`_id` pair is written atomically and the regular factories
		// don't overwrite them. Each retry resamples — a collision on a
		// UNIQUE constraint involving the poly columns re-draws the parent.
		polyAssigned := poly.assign(rowVals, e.pool, rng)
		for i, colName := range cols {
			if polyAssigned[i] {
				continue
			}
			spec := tbl.Columns[colName]
			val, err := e.generateValue(ref, colName, spec, row, rng)
			if err != nil {
				return false, err
			}
			rowVals[i] = val
			if isPK[i] {
				e.pool.add(ref.Schema, ref.Name, colName, val)
			}
		}
		ok, canRetry := tracker.check(rowVals)
		if ok {
			return true, nil
		}
		if !canRetry {
			// Collision in an all-literal unique set — resampling will produce
			// identical tuples indefinitely. Drop without burning retries.
			e.pool.restore(snap)
			return false, nil
		}
	}
	e.pool.restore(snap)
	return false, nil
}

func isPKColumn(tbl *config.Table, name string) bool {
	if len(tbl.PrimaryKey) > 0 {
		for _, pk := range tbl.PrimaryKey {
			if pk == name {
				return true
			}
		}
		return false
	}
	return name == "id"
}

// activeColumns returns the emission order for a table. PK columns come first
// (so the FK pool is populated before any self-FK in the same row can be
// generated), then ColumnOrder, then remaining columns alphabetically. Column
// names are returned once even if they appear in multiple buckets.
func activeColumns(tbl *config.Table) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(tbl.Columns))
	add := func(name string) {
		if seen[name] {
			return
		}
		spec, ok := tbl.Columns[name]
		if !ok || spec.Removed {
			return
		}
		out = append(out, name)
		seen[name] = true
	}
	pks := tbl.PrimaryKey
	if len(pks) == 0 {
		if _, ok := tbl.Columns["id"]; ok {
			pks = []string{"id"}
		}
	}
	for _, name := range pks {
		add(name)
	}
	for _, name := range tbl.ColumnOrder {
		add(name)
	}
	rest := make([]string, 0, len(tbl.Columns))
	for name, spec := range tbl.Columns {
		if !seen[name] && !spec.Removed {
			rest = append(rest, name)
		}
	}
	sort.Strings(rest)
	for _, name := range rest {
		add(name)
	}
	return out
}

func (e *Emitter) generateValue(ref relations.TableRef, colName string, spec *config.ColumnSpec, row int, rng *rand.Rand) (any, error) {
	// Literal value — emitted as-is for every row.
	if spec.Value != nil {
		return spec.Value, nil
	}
	// JSON shape defined inline — build object recursively, skip mechanism.
	if len(spec.Values) > 0 {
		obj := e.buildJSONObject(ref, spec.Values, row, rng)
		b, err := json.Marshal(obj)
		if err != nil {
			return nil, fmt.Errorf("marshal JSON for %s.%s row %d: %w", ref.Name, colName, row, err)
		}
		return string(b), nil
	}
	val := e.runFactory(ref, colName, spec, row, rng)
	// Enforce varchar(N)/char(N) ceilings inferred from the schema. Truncation
	// is a last-mile guard — factories that know their domain (uuid, token,
	// checksum) can still overflow narrow columns when a user declared an
	// unusually small N. Runes, not bytes, so multi-byte UTF-8 is not split.
	if ml, ok := spec.Params["max_len"].(int); ok && ml > 0 {
		if s, ok := val.(string); ok {
			val = truncateRunes(s, ml)
		}
	}
	return val, nil
}

func truncateRunes(s string, n int) string {
	if n <= 0 {
		return ""
	}
	if len(s) <= n {
		return s
	}
	runes := []rune(s)
	if len(runes) <= n {
		return s
	}
	return string(runes[:n])
}

func (e *Emitter) runFactory(ref relations.TableRef, colName string, spec *config.ColumnSpec, row int, rng *rand.Rand) any {
	m, ok := e.reg.Get(spec.Factory)
	if !ok {
		warnKey := ref.Key() + "." + colName + ":" + spec.Factory
		if !e.pool.warnedFactory[warnKey] {
			fmt.Fprintf(os.Stderr, "seed: warning: unknown factory %q for %s.%s — emitting NULL\n", spec.Factory, ref.Key(), colName)
			e.pool.warnedFactory[warnKey] = true
		}
		return nil
	}
	apiCol := seedapi.Column{
		Schema: ref.Schema, Table: ref.Name, Name: colName,
		DataType: spec.DataType, Nullable: spec.Nullable,
	}
	if target, _ := spec.Params["target"].(string); target != "" {
		apiCol.FKTarget = target
	}
	return m.Generate(seedapi.GenContext{
		Column: apiCol,
		Row:    row,
		Rng:    rng,
		Params: seedapi.Params(spec.Params),
		FKPool: e.pool,
		Locale: e.opts.Locale,
	})
}

const maxJSONDepth = 20

// buildJSONObject recursively builds a map[string]any from a Values spec.
// Nested Values entries produce nested maps; leaf entries call the mechanism.
// Recursion is capped at maxJSONDepth to prevent stack overflow on cyclic configs.
func (e *Emitter) buildJSONObject(ref relations.TableRef, values map[string]*config.ColumnSpec, row int, rng *rand.Rand) map[string]any {
	return e.buildJSONObjectDepth(ref, values, row, rng, 0)
}

func (e *Emitter) buildJSONObjectDepth(ref relations.TableRef, values map[string]*config.ColumnSpec, row int, rng *rand.Rand, depth int) map[string]any {
	obj := make(map[string]any, len(values))
	if depth >= maxJSONDepth {
		return obj
	}
	for k, spec := range values {
		if spec.Value != nil {
			obj[k] = spec.Value
			continue
		}
		if len(spec.Values) > 0 {
			obj[k] = e.buildJSONObjectDepth(ref, spec.Values, row, rng, depth+1)
			continue
		}
		obj[k] = e.runFactory(ref, k, spec, row, rng)
	}
	return obj
}

func formatSQL(v any) string {
	if v == nil {
		return "NULL"
	}
	switch x := v.(type) {
	case string:
		return quoteString(x)
	case bool:
		if x {
			return "TRUE"
		}
		return "FALSE"
	case int:
		return fmt.Sprintf("%d", x)
	case int32:
		return fmt.Sprintf("%d", x)
	case int64:
		return fmt.Sprintf("%d", x)
	case uint:
		return fmt.Sprintf("%d", x)
	case uint32:
		return fmt.Sprintf("%d", x)
	case uint64:
		return fmt.Sprintf("%d", x)
	case float32:
		return formatFloat(float64(x))
	case float64:
		return formatFloat(x)
	case time.Time:
		return "'" + x.UTC().Format("2006-01-02 15:04:05.999999-07") + "'"
	case []byte:
		// Postgres bytea hex format — unambiguous regardless of standard_conforming_strings.
		return `'\x` + fmt.Sprintf("%x", x) + "'"
	case []any:
		parts := make([]string, len(x))
		for i, el := range x {
			parts[i] = formatSQL(el)
		}
		return "ARRAY[" + strings.Join(parts, ", ") + "]"
	case seedapi.Cast:
		return formatSQL(x.Value) + "::" + x.Type
	case fmt.Stringer:
		return quoteString(x.String())
	default:
		return quoteString(fmt.Sprint(x))
	}
}

// quoteString escapes a Go string into a PG string literal. The E'' prefix
// forces C-style escape semantics, guaranteeing correct handling of
// backslashes regardless of the session's standard_conforming_strings setting.
// All ASCII control characters are escaped as \xNN so psql and common
// downstream tooling never choke on raw controls.
func quoteString(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 4)
	b.WriteString("E'")
	for _, r := range s {
		switch {
		case r == '\'':
			b.WriteString(`''`)
		case r == '\\':
			b.WriteString(`\\`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		case r == 0:
			// NUL is not representable in Postgres text — drop it explicitly.
		case r < 0x20:
			fmt.Fprintf(&b, `\x%02x`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

func formatFloat(f float64) string {
	if math.IsNaN(f) {
		return "'NaN'::float8"
	}
	if math.IsInf(f, 1) {
		return "'Infinity'::float8"
	}
	if math.IsInf(f, -1) {
		return "'-Infinity'::float8"
	}
	// 'f' with -1 precision keeps values readable (e.g. `1234567.89` rather
	// than `1.23456789e+06`). For extreme magnitudes Go falls back to the
	// shortest form that round-trips.
	abs := math.Abs(f)
	if abs != 0 && (abs < 1e-4 || abs >= 1e15) {
		return strconv.FormatFloat(f, 'g', -1, 64)
	}
	return strconv.FormatFloat(f, 'f', -1, 64)
}

func quoteIdent(s string) string {
	return "\"" + strings.ReplaceAll(s, "\"", "\"\"") + "\""
}

// memoryPool keeps already-generated PKs for FK sampling.
// Not safe for concurrent use; Emitter.Emit is single-threaded.
type memoryPool struct {
	byKey         map[string][]any
	warnedFactory map[string]bool // deduplicates unknown-factory warnings
}

func newMemoryPool() *memoryPool {
	return &memoryPool{
		byKey:         map[string][]any{},
		warnedFactory: map[string]bool{},
	}
}

func (p *memoryPool) add(schemaName, table, column string, v any) {
	if v == nil {
		return
	}
	k := schemaName + "." + table + "." + column
	p.byKey[k] = append(p.byKey[k], v)
}

func (p *memoryPool) Pick(schemaName, table, column string, rng *rand.Rand) (any, bool) {
	k := schemaName + "." + table + "." + column
	pool := p.byKey[k]
	if len(pool) == 0 {
		return nil, false
	}
	return pool[rng.IntN(len(pool))], true
}

// poolSnapshot records the lengths of this table's PK columns in the pool,
// so a failed row attempt can be rolled back without affecting entries from
// earlier tables.
type poolSnapshot struct {
	prefix  string
	lengths map[string]int
}

func (p *memoryPool) snapshot(schemaName, table string) poolSnapshot {
	prefix := schemaName + "." + table + "."
	snap := poolSnapshot{prefix: prefix, lengths: map[string]int{}}
	for k, vals := range p.byKey {
		if strings.HasPrefix(k, prefix) {
			snap.lengths[k] = len(vals)
		}
	}
	return snap
}

// restore truncates this table's pool columns back to the recorded lengths.
// Keys that didn't exist at snapshot time are cleared entirely.
func (p *memoryPool) restore(snap poolSnapshot) {
	for k, vals := range p.byKey {
		if !strings.HasPrefix(k, snap.prefix) {
			continue
		}
		n, ok := snap.lengths[k]
		if !ok {
			p.byKey[k] = nil
			continue
		}
		if len(vals) > n {
			p.byKey[k] = vals[:n]
		}
	}
}
