-- Generated by seed CLI at <TIMESTAMP>
BEGIN;

-- public.reviews (3 rows)
INSERT INTO "public"."reviews" ("id", "comment", "rating") VALUES
  (1, E'comment_0', 3),
  (2, E'comment_1', 5),
  (3, E'comment_2', 4);
COMMIT;
