-- Generated by seed CLI at <TIMESTAMP>
BEGIN;

-- public.categories (5 rows)
INSERT INTO "public"."categories" ("id", "name", "parent_id") VALUES
  (1, E'Arjun Novak', 1),
  (2, E'Mia Mensah', 1),
  (3, E'Hugo Schneider', 1),
  (4, E'Nia Zhang', 3),
  (5, E'Ming Mansour', 5);

-- public.customers (5 rows)
INSERT INTO "public"."customers" ("id", "created_at", "email", "first_name", "last_name") VALUES
  (1, '2024-07-28 22:05:27.781193+00', E'user0_4093@example.com', E'Ren', E'Mansour'),
  (2, '2024-10-30 02:25:24.637887+00', E'user1_3257@example.com', E'Oliver', E'Dubois'),
  (3, '2024-09-21 12:50:20.918602+00', E'user2_9293@example.com', E'Noah', E'Yamamoto'),
  (4, '2024-12-14 03:08:41.334948+00', E'user3_4400@example.com', E'Yusuf', E'Martin'),
  (5, '2024-05-31 23:19:11.449406+00', E'user4_294@example.com', E'Lucas', E'Kowalski');

-- public.products (5 rows)
INSERT INTO "public"."products" ("id", "active", "category_id", "metadata", "name", "price", "released_at", "signature", "tags") VALUES
  (E'075b0852-9970-4408-aaf3-b6f1aec5e6dc', TRUE, 3, E'{"row":0}', E'Jian Kowalski', 5074.27, E'2027-12-29', '\xf43c17172855f26f95081e00dc7452cf', ARRAY[E'item_0_0', E'item_0_1', E'item_0_2']),
  (E'637e4d44-ffab-45a2-9a9d-a88caeb97b17', TRUE, 4, E'{"row":1}', E'Felix Mensah', 440.83, E'2025-10-03', '\x4b413d2b6ca3e1876687a09328e94421', ARRAY[E'item_1_0', E'item_1_1', E'item_1_2']),
  (E'ae54a6db-aa02-489a-8f4c-abf4aec08be8', FALSE, 2, E'{"row":2}', E'Ying Qureshi', 8620.75, E'2024-12-31', '\x0dfef3c75d54d621df0254dbd0f513a1', ARRAY[E'item_2_0', E'item_2_1', E'item_2_2']),
  (E'f4d2c9b9-7634-4723-929a-4ad02a6a1c27', TRUE, 3, E'{"row":3}', E'Fatima Singh', 5980.55, E'2025-05-18', '\x45662fa33e30337e81ff0f603d64ffc2', ARRAY[E'item_3_0', E'item_3_1', E'item_3_2']),
  (E'49364a1a-b4e8-4c51-a98e-9b6161edaa0b', FALSE, 1, E'{"row":4}', E'Chloé Mensah', 1590.09, E'2025-01-01', '\xfed0fa63d5acf6317eab1bc736c8a72a', ARRAY[E'item_4_0', E'item_4_1', E'item_4_2']);

-- public.orders (5 rows)
INSERT INTO "public"."orders" ("id", "created_at", "customer_id", "notes", "product_id", "status", "total_amount") VALUES
  (1, '2024-04-23 19:53:45.534834+00', 1, E'notes_0', E'075b0852-9970-4408-aaf3-b6f1aec5e6dc', E'pending', 1704.31),
  (2, '2024-06-27 03:24:10.931147+00', 1, E'notes_1', E'ae54a6db-aa02-489a-8f4c-abf4aec08be8', E'shipped', 3039.17),
  (3, '2024-05-12 19:33:32.760204+00', 5, E'notes_2', E'637e4d44-ffab-45a2-9a9d-a88caeb97b17', E'pending', 1022.6),
  (4, '2024-04-21 11:29:50.377961+00', 4, E'notes_3', E'075b0852-9970-4408-aaf3-b6f1aec5e6dc', E'paid', 4086.85),
  (5, '2024-03-18 11:43:10.570473+00', 5, E'notes_4', E'637e4d44-ffab-45a2-9a9d-a88caeb97b17', E'shipped', 8050.92);
COMMIT;
