package seed

import (
	"reflect"
	"testing"
)

func TestSplitStatements(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  []string
	}{
		{
			name:  "simple two statements",
			input: "BEGIN;\nCOMMIT;",
			want:  []string{"BEGIN", "COMMIT"},
		},
		{
			name:  "semicolon inside string literal preserved",
			input: `INSERT INTO t (c) VALUES ('a;b');`,
			want:  []string{`INSERT INTO t (c) VALUES ('a;b')`},
		},
		{
			name:  "escaped single-quote inside string",
			input: `INSERT INTO t (c) VALUES ('it''s fine');`,
			want:  []string{`INSERT INTO t (c) VALUES ('it''s fine')`},
		},
		{
			name:  "line comment with semicolon ignored",
			input: "-- header; comment\nBEGIN;\nCOMMIT;",
			want:  []string{"BEGIN", "COMMIT"},
		},
		{
			name:  "sqlemit-style header comment",
			input: "-- Generated by seed CLI at 2024-01-01T00:00:00Z\nBEGIN;\nCOMMIT;",
			want:  []string{"BEGIN", "COMMIT"},
		},
		{
			name:  "multi-row insert",
			input: "INSERT INTO t (id) VALUES\n  (1),\n  (2);",
			want:  []string{"INSERT INTO t (id) VALUES\n  (1),\n  (2)"},
		},
		{
			name:  "empty input",
			input: "",
			want:  nil,
		},
		{
			name:  "whitespace only",
			input: "   \n  \t  ",
			want:  nil,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := splitStatements(tc.input)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("splitStatements(%q)\n  got  %v\n  want %v", tc.input, got, tc.want)
			}
		})
	}
}
